### ISSUE TITLE
Touch navigation does not work when slider is contained in a flex element

### ISSUE THREAD

**Issue by floatingdino** [ganlanyuan/tiny-slider#133]
__Issue description__:  Trying to swipe through slides fails, and the navigation bullets collapse after swiping when the container uses flex eg:
```
<header style="display:flex">
  <div class="slider">
    <div class="slide"></div>
    <div class="slide"></div>
  </div>
</header>
```

__Demo link/slider setting__:   This seems to occur regardless of settings, but below is my use case.
```
tns({
    container: document.querySelector('.slider'),
    speed:300,
    autoplay:true,
    autoplayTimeout: 12000 + ((Math.random() - 0.5) * 1000),
    autoplayButton:false,
    autoplayHoverPause:true,
    controls:false,
    controlsText: [],
    nav: true
})
```

_Tiny-slider version_:   2.5.0, also observed on 2.4.1 and 2.3.6
_Browser name && version_:  Chrome 63 device previews, iOS Chrome 63
_OS name && version_:   macOS Sierra 10.12.6, iOS 11.2.2

**Comment by ganlanyuan** [comment]
This looks like a CSS issue.
I will look closer to it when I get a chance.

**Comment by ganlanyuan** [comment]
Hey, sorry for the late response
In your case, you just need to add a extra slider wrapper which need to be set `width: 100%`, because `flexbox` will shrink everything inside to their minimum sizes.
Demo: https://codepen.io/ganlanyuan/pen/xpmyQB
You can test it on your mobile with: https://s.codepen.io/ganlanyuan/debug/xpmyQB/yPMJjGmZnQoM
