### ISSUE TITLE
Add startIndex to reponsive-able options

### ISSUE THREAD

**Issue by rejas** [ganlanyuan/tiny-slider#138]
Hi again
wondering if it would be possible to add startIndex to the options that can be specified seperatly for different media queries in the reponsive field?

**Comment by ganlanyuan** [comment]
May I know the reason why you want to have different `startIndex`s for each media query?

**Comment by rejas** [comment]
Scenario is:
- mobile view: 1 slide visible, carousel starts with index 0 (first slide)
- desktop view: 3 slides visible, carousel starts with index 0 in the middle (hence startIndex will be last slide)

What dig into the code myself for creating a PR (or using my fork if you dont like the idea) but then I cannot seem to find the file "www/package.json" with all devDependencies in it. Isnt that added to the git?

**Comment by ganlanyuan** [comment]
Hi, it's added in [this commit](https://github.com/ganlanyuan/tiny-slider/commit/fd3a36b204f2b5b9d009198608b109e6053f047b) and will be delivered in next release.
Since I'm using docker in this project, the "package.json" is from the [docker image](https://github.com/ganlanyuan/dockerfile/blob/v2.5.0/web/package.json) which will not shown here.

**Comment by ganlanyuan** [comment]
Added in [v2.5.1](https://github.com/ganlanyuan/tiny-slider/releases/tag/v2.5.1)

**Comment by rejas** [comment]
Awesome. Once again: Thank you very much!
