### ISSUE TITLE
When only one slide in  the slider, it still  displays many

### ISSUE THREAD

**Issue by faboulaws** [ganlanyuan/tiny-slider#14]
When the slider has only 1 slide and loop=true, the user could still navigate back and forth. However, the user navigates to the same slide, which is confusing for the user, since he sees the same slide all the time.

**Comment by ganlanyuan** [comment]
Hey,
From [v0.6.2](https://github.com/ganlanyuan/tiny-slider/tree/v0.6.2), if the slide item count is the same with the **items** in the options, the **nav** and **controls** will not be displayed.
Would you mind to check it?

**Comment by faboulaws** [comment]
I checked and the **items=1** option does not fix this issue. Why do we need the items option if the slider can detect the number of slide in the slider?

**Comment by ganlanyuan** [comment]
> I checked and the items=1 option does not fix this issue. 

Are you able to make a demo?
> Why do we need the items option if the slider can detect the number of slide in the slider?

Even though we can detect the slider number, but you may have different option. E.g. the slider number is 8, but I want to show only 3 in a page.

> Also if there is only 1 slide in the slider, there is no need for extra clones.

The extra clones are for the `loop` and is been done in the initialization stage. It's specially useful when you have many breakpoints. I clone it first, because I don't want to check the init for every resize event.   
While, in reality, if you know you will have only one slide, why do slider any more?
