### ISSUE TITLE
destroy callback or reload function

### ISSUE THREAD

**Issue by ninjaonsafari** [ganlanyuan/tiny-slider#157]
__Issue description__:  
I haven't found to dynamically add / remove slides.
There is also no reload().

Could you add a reload() or a callback for the destroy function, so we could reinit the slider after added / removed slides?

_Tiny-slider version_:   2.5.2
_Browser name && version_:  *
_OS name && version_:   *

**Comment by ganlanyuan** [comment]
Just add a new method `rebuild()`, please refer to [here](https://github.com/ganlanyuan/tiny-slider#rebuild).
For dynamically add/remove slides, it's much more complicated. I will consider this feature later.

**Comment by ninjaonsafari** [comment]
Thank you! Exactly what I need.
could you deploy the new version on npm?

**Comment by leecollings** [comment]
Hi, I'm having a problem with this rebuild, as I want to rebuild as part of a Wordpress ajax call. The initial carousel code is loading before the child divs are created, creating the 'No slides found' warning.

However, as part of my ajax function that creates the children, whe I call slider.destroy().rebuilt() I get:

> Uncaught TypeError: Cannot read property 'destroy' of undefined

So how can I look for the slider first, as I believe this is because I'm trying to call destroy before the carousel is actually created in the first place...

**Comment by S1SYPHOS** [comment]
Hey there,
I would like to see a callback for the `destroy` method, since I want to 'tell' the console after I destroyed the slider .. just to be sure :D
