### ISSUE TITLE
Mousedrag doesn't release the slider after mouseUp

### ISSUE THREAD

**Issue by viktorlarsson** [ganlanyuan/tiny-slider#186]
__Issue description__:  
Currently having an issue (with both horizontal and vertical axis) where if you click one of the items in the slider it keeps dragging the slider. Seems as it isn't releasing it after mouseUp, see the gif below. In the gif I am not holding down the mouse but I am releasing it and it gets stuck. I've tried swipeAngle but that doesn't seem to help.

__Demo link/slider setting__:   
![ezgif-5-30d5fb2c36](https://user-images.githubusercontent.com/722315/38988533-cc186d2a-43d3-11e8-8acc-c3c899158e36.gif)

_Tiny-slider version_:   2.6.0
_Browser name && version_:   Chrome (latest)
_OS name && version_:   Windows 10

**Comment by jondotblack** [comment]
I'm experiencing the same issue - the mouse remains 'stuck' and the carousel continues to drag even though I've clicked and released.

```
options: {
  items: 2,
  edgePadding: 0,
  slideBy: 1,
  loop: false,
  mouseDrag: true,
  nav: false,
  responsive: {
    577: {
      items: 3,
      slideBy: 3,
    },
    992: {
      edgePadding: 40,
      items: 3,
      slideBy: 3,
    }
  }
}
```

**Comment by viktorlarsson** [comment]
Any idea here @ganlanyuan ?

**Comment by ganlanyuan** [comment]
Will check this shortly.

**Comment by viktorlarsson** [comment]
You are fantastic!

**Comment by ganlanyuan** [comment]
Hi, May I know your slider options?

**Comment by viktorlarsson** [comment]
@ganlanyuan 

``` 
options: {
  axis: 'vertical',
  loop: false,
  mouseDrag: true,
  items: 3,
  controlsText: ['',''],
  gutter: 20,
  nav:  true,
  swipeAngle: false // tried everything here but same issue occurs
  }
}
```

**Comment by viktorlarsson** [comment]
Cheers! I tried it out bit it kinda made it worse :/

![slider](https://user-images.githubusercontent.com/722315/40041983-1c39acfa-5820-11e8-8cc0-b860b93d8ab8.gif)

**Comment by ganlanyuan** [comment]
Could you create a demo on codepen or somewhere?
Because I actually couldn't reproduce the issue on my side.

**Comment by Aharito** [comment]
@ganlanyuan Thank you for the raf branch, I had the same bug on this configuration:

_Tiny-slider version: 2.6.0
Browser name && version: Chrome (latest)
OS name && version: Windows 7_

But with the raf branch code all is Ok.

**Comment by Aharito** [comment]
@ganlanyuan Unfortunately, more extensive testing has shown that the error still exists.

Error occurs when mouseDrag: true. Then mouse click on the slider element, the elements of the slider are move forward.

**Comment by sachinsinghi** [comment]
@ganlanyuan ,
Any update on the issue?

**Comment by sachinsinghi** [comment]
Here is the codepen https://codepen.io/ssinghi/pen/OZqWXp

**Comment by viktorlarsson** [comment]
@ganlanyuan Seems to be working! Fantastic!

**Comment by DMCK96** [comment]
Can confirm in v2.8.1 and 2.8.2 this bug is present. Had to disable mouseDrag for the time being. Ocurring on a div element with an image background.

**Comment by ganlanyuan** [comment]
@DMCK96 Could you make a demo?
I didn't see this issue (on div elements with background image) when tested locally.

**Comment by mitch-rickman** [comment]
I'm experiencing the same issue on version 2.8.5 with background images on the slides and the following settings?
`{
          items: 4,
          lazyLoad: true,
          loop: false,
          nav: false,
          controls: false,
          arrows: false,
          container: this.navSliderNode,
          mouseDrag: true,
          fixedWidth: 70,
          gutter: 8,
          responsive: {
            768: {
                fixedWidth: 140,
            },
}`

HTML structure is:
`<div class="slider">
    <div class="slide">
        <button style="background-image: url('...')">
            <img src="..." />
        </button>
    <div>
    ...
</div>`

I assume the script is listening for a mouse up / mouse down function, but is there any possibility that the propagation is being stopped by another event somewhere? The issue occurs about 80% of the time I use the slider, so 20% of the time it works correctly.

**Comment by mitch-rickman** [comment]
Update, So I incorrectly updated my version of tiny slider before, after actually updating the slider version to the latest things started to work for my slider... but the issue appeared on another slider.

The new broken slider was functioning before the update. I did some testing with the latest version of the slider and I realized the issue was that my slider had a full width and height <a> tag, so I am assuming there were event conflicts.

Digging deeper, I started looking at the `onPanStart` method, which uses on the `preventDefaultBehavior` function upon certain conditions. I adjusted the conditional (`!isTouchEvent(e) && ['img', 'a'].indexOf(getLowerCaseNodeName(getTarget(e))) >= 0`) so `preventDefaultBehavior` would be called every time the event is not a touch event. This seemed to be fix the issue, and all of my sliders are running as expected.

@ganlanyuan, Can you foresee the removal of ` && ['img', 'a'].indexOf(getLowerCaseNodeName(getTarget(e))) >= 0` causing any issues? 

Also, do you have instructions on how to get the build running. I tried `npm install`, `bower install` and then `gulp min` found out there were a handful of missing packages and a missing /www/package.json file
