### ISSUE TITLE
Rebuilding multiple instances causing error

### ISSUE THREAD

**Issue by kylegoines** [ganlanyuan/tiny-slider#250]
(making a seperate ticket for this bug)

I have inited multiple instances of the tiny-slider with using a collection of querySelector('.elem')
my options are

```
this.slideshow  = tns( {
            container: document.querySelector('.js-slideshow)
            items: 1,
        } );
```

I am able to this.slideshow.destroy() with expected results. But when I try to `this.slideshow.rebuild()` i am given the error `Uncaught TypeError: Cannot read property 'clientWidth' of null`

However if I init `tns` slider like this
```
this.slideshow  = tns( {
            container: '.js-slideshow', // note i am using the string class here
            items: 1,
        } );
```
this will let me use `this.slideshow.destroy()` and  `this.slideshow.rebuild()` correctly.

i am using 
v2.8.4
Chome Mac OS

**Comment by planktonic** [comment]
In case it helps: I have the same issue when instantiating only one slider. I’m using v2.8.4, and destroying then re-instantiating a completely new `tns()` (not `rebuild()`) inside a `window.matchMedia` listener (I cannot use tns’ `responsive` options as they don’t cover everything I need to change).

I was also getting the dreaded `Uncaught TypeError: Cannot read property 'clientWidth' of null` with both `v2.8.3` and `2.8.4` (tested in latest Chrome, Firefox, & safari), when instantiating the new slider, but passing a string selector for `container` instead of a DOM element fixed it! Thanks so much for the tip @kylegoines 🙌

**Comment by ganlanyuan** [comment]
Check out the latest commit.
This should be fixed.

**Comment by ganlanyuan** [comment]
Should be fixed in v2.8.5

**Comment by ThaoD5** [comment]
I confirm having the same struggle as @planktonic, it is not possible for me to destroy & rebuild / re-define a slider with an object as a container.

With the string, I am getting another issue after one reset : 
`Failed to set the 'outerHTML' property on 'Element': This element has no parent node`

**Comment by ganlanyuan** [comment]
@CharlesKumar If you want your slides have 100% width, you can use `items: 1` instead of `fixedWidth`

**Comment by CharlesKumar** [comment]
@ganlanyuan yeah i tried items: 1, it is not helping

Now I used responsive options (because it is already a window resize event listener)

why fixedWidth: '100%' breaks next/;prev, mouseDrag ??

**Comment by ganlanyuan** [comment]
Please refer to https://github.com/ganlanyuan/tiny-slider#features
`100%` should be percentage width, while `fixedWidth` only accept a positive integer value
