### ISSUE TITLE
End of life?

### ISSUE THREAD

**Issue by marcelaerts** [ganlanyuan/tiny-slider#568]
Hi there, is this plugin end of life? A lot of issues and last commit over 6 months ago? It's really easy to use and wish it will continue.

**Comment by marcj** [comment]
Yepp, dead. Time to switch.

**Comment by michaelegan** [comment]
Anybody have similar alternatives to share?

**Comment by lorvent** [comment]
oops, i am just planning to switch from owl-carousel to this one.
now this is also dead?

**Comment by Ahmaddahshan** [comment]
@michaelegan try Slick http://kenwheeler.github.io/slick/
or
Flickity https://flickity.metafizzy.co/

**Comment by marcelaerts** [comment]
https://swiperjs.com/

**Comment by Teisi** [comment]
switch to what?
- swiper? To big.
- Slick - only with jquery so that is not an alternative
- flickity? not open source/free and it seems that sich slider is dead too

**Comment by marcelaerts** [comment]
@Teisi , what do you suggest?

**Comment by Teisi** [comment]
@marcelaerts 
I don't know, that's why I'm asking... :)

**Comment by leastbad** [comment]
It is a sad statement on the state of JS ecosystem standards when a library that was last updated ~7 months ago is declared "dead" and "EOL".

"Time to switch". At this rate of change, why rely on 3rd-party code?

**Comment by marcelaerts** [comment]
@leastbad as you can clearly see I asked if it was EOL. In my case issues not being answered is more important then no updates. I just want to know if the developer(s) are going to continue.

**Comment by marcj** [comment]
@leastbad calm down. Its daily business in open-source, especially in fast moving JS/frontend business, that if you don't keep your project up2date and responsive, people will quickly pick a new one. Especially in a field like this slider that is not a third-party dependency and could break anytime when a new IE, Chrome, or mobile Safari release is being published.

Also let's be honest, until you pay this guy, this procedure is going on and on. Obviously he has no priority for this project since half a year and doesn't even answer to this kind of issues. 

I agree with @marcelaerts that being responsive to issues is more important than actual code changes. A software can be feature complete, but questions/bugs will always pop up.

However, no pressure to the author. I know the feeling of letting a project go. People should just accept that free code is often limited and has a short lifetime. Also most of the time (not always), even when the maintainer answers now, that doesn't mean anything as only actions count. He may simply have a bad conscience. You should only evaluate a OSS project by actions, never by promises, since the author is not accountable for anything -- only if you a contract and pay him.

**Comment by Ahmaddahshan** [comment]
Well said 👌🏼 @marcj

**Comment by leastbad** [comment]
No. Not well said.

My position is by definition calm; you're the ones acting like a gang of tweakers because someone took half a year off from working on an open-source project. The notion that something modified in the last year is abandonware is fundamentally absurd. All of this talk about having a bad conscience and actions mattering more than promises sounds like a screenplay for a cliched crime movie.

If this is totally fine and normal for the JS ecosystem - to decide the creator of a carousel library might have a "bad conscience" - then the culture of your ecosystem is toxic and immature, because you're operating under the mistaken belief that August 2019 is old and outdated. tiny-slider seems like a perfectly good library. If there's something wrong with it that is burning your house down, fork it and fix it. That's what we do in literally every other language community. It's completely normal to not see changes to important libraries for years at a time. It's not because they are broken, it's because they are stable.

**Comment by marcj** [comment]
You have a lot of false conclusions and disrespectful accusations here. 

> That's what we do in literally every other language community

You obviously don't understand the dynamics of big open source communities. The vast majority of people don't fork and fix libraries. They switch just to another one if the current one doesn't suit anymore. You have plenty of alternatives to chose from.
Only in smaller communities like your Ruby community where you're coming from might it be the case that people fork and fix more. I know this from the C++ community, where forking and fixing is also way more common. You barely see "Is this end of life" threads, but it's very common in the JS community. But that's not the result of a nicer (c++/ruby/...) community, but plain from the fact that you run out of alternative libraries -- precisely because the (active) community is small. The by far biggest developer community of the world works here differently.

All of your other accusations here especially about the bad conscience is something I won't try to explain to you since you obviously are neither interested in a polite discussion nor do you have the experience of being a maintainer of a successful library in this community. So you better back off and stop your wild accusations.

Instead of accusing us of toxic behavior and other wild stuff, you should get used to this simple fact.

**Comment by leastbad** [comment]
@marcj You're the one who suggested that the project owned might have a "bad conscience" - not me.

As for whether it's simple, a fact, whether it's something I should or have to "get used to"... all of these things are choices you have to make. Do you feel like you deserve better, or do you not? I clearly have chosen to put my time into communities that don't equate old == bad.

Meanwhile: I stand by the fact that you all sound like a bunch of raving tweakers.

**Comment by smartcorestudio** [comment]
@michaelegan https://splidejs.com - modern, lightweight, customizable, free

**Comment by lems3** [comment]
For people recommending Slick : We were looking to move away from it. It has a lot of issues and a real absence of support. Author have dropped the project and tried to give it to other people, and it clearly failed.

**Comment by Whiax** [comment]
What's the matter? If it works for most usages, support or updates aren't required. Do we expect to have the same lib redeveloped over and over? owl => tiny-slider => splide => etc..

**Comment by alvinkonda** [comment]
thumbs up for @smartcorestudio for sharing splidejs.com. Looks perfect for my project

**Comment by ADDISON74** [comment]
I was a big fan of Owl Carousel for many years. Seeing Tiny Slider going in the same direction like OC I started to evaluate a replacement and I found Splide JS to be a perfect choice. Tons of options packed in a lightweight js file. It is 10 times less as size comparing with Swiper JS. The developer solved a conflict with Prototype.js library in less than an hour from reporting the issue on GitHub. If I will learn to create my own extensions/components to extend its functionality I will be very happy. Probably if more of us will use it we will get new features like complex transitions. At least for sliding videos (HTML, YouTube, Vimeo) it works as expected.

**Comment by ganlanyuan** [comment]
Thanks for your concerns and interest in this project and sorry for the very late response. 
Just want to let you know, I will continue to work on this project. 
I won't be able to check the issues and PRs everyday but at least 2 times a week.

**Comment by leastbad** [comment]
Thanks for all of your hard work, Willliam.

**Comment by ganlanyuan** [comment]
You’re welcome

**Comment by AeShevch** [comment]
`[Glide.js](https://glidejs.com/)`

**Comment by nicped** [comment]
We just made this slider - https://github.com/dynamicweb/swiffy-slider, less than 3.5kb in CSS and Vanilla js

**Comment by Yapacdev** [comment]
I advise all people to migrate to: https://react-slick.neostack.com/
I migrated from OwlCarousel to Slick in like a half day, and it improved my app alot

**Comment by blackwelllearning** [comment]
Hi @ganlanyuan :)

Thank you for creating this replacement to Owl carousel. Moving to this from that meant I didn't need to change much HTML basically keeping the same code structure and classes. Was a dream to make that switch. This was many moons ago, I have to add, so not a recent change but a well loved one. x

I have forked and raised a PR for a WCAG 2.1 Accessibility change, essential for todays EU, and other countries', Accessibility laws and is not allowing us to be fully accessible. 

Any chance you could take a look at the PR for us? I have no intention of switching again :)

You would also being doing a great service to the entire internet community.

**Comment by nicped** [comment]
This component is stone dead:

Never use a JS based component if you want to be WCAG 2.1 accessible. You need a markup based version instead. Or at least something made in recent years.

Also you could argue that carousels as a concepts will never be WCAG compliant as they are a really weird UX concept in general - maybe only useful for scrolling images on a product page...

<img width="948" height="195" alt="Image" src="https://github.com/user-attachments/assets/3cf44f9d-c0e8-472b-8028-175dd3d941c4" />

**Comment by blackwelllearning** [comment]
Thanks @nicped :)

> This component is stone dead:
That is a shame.

Do you happen to know how I can get our fork of the repo to build as per the most recent version of the code?

Following the README in the contributing section of this repo, I was unable to get the code to match and I saw nothing that led me to make it work.

If I can get it to build the same then I can continue to use our version, with the WCAG fixes we have made.

> 
> Never use a JS based component if you want to be WCAG 2.1 accessible. You need a markup based version instead. Or at least something made in recent years.

I am a big supporter of no JS but atm our road map for development, replacing this part of our site isn't in view. And this does everything we want it to do functionally. It just needs a couple of code removals to be compliant :)

As far as our accessibility tools and checkers are concerned, 2 top tier checkers recommended by W3C and WebAim, there is currently no issue with this component with regards to WCAG 2.1 that we have found so far, other than the `aria-hidden` attrs being on hidden content, which is all we have removed so far but we are unable to confirm that's all that required as it doesn't build correctly as a module.

> 
> Also you could argue that carousels as a concepts will never be WCAG compliant as they are a really weird UX concept in general - maybe only useful for scrolling images on a product page...

We do in fact use it for exactly that, and with some added text and buy buttons :)

I don't know how they will "never be WCAG compliant" considering we haven't had a failure for any of it other than the `aria` bits. Can you put me in the direction of the requirements these fail for WCAG please? If this is in fact true then maybe we will bring forward the road map to change this.

If we can get a working repo I'll sort out all the accessibility issues that may arise from it so we can be a fully compliant site.

As for UX, even though A11y and UX are related, the UX for an accessible user is entirely different for a competent visual user. A user relying on Accessibility to browse the site needs to get to the content with their tools which relies more on a well structured DOM rather than fancy looking sliders. Nothing in this slider stops that, again, other than the `aria` issue, that we can find so far.

Sliding content isn't that weird an UX concept though. It's been pretty successful over the years. Such as smart phone home screen navigation and even e-readers and PDF viewers, when moving between pages, and OS GUI folder views have also used this technique for scrolling through photos when choosing 'big' view mode to see them better.

Bad UX does exist so it all depends how it's being used and this JS component has many options.

I think our use of this and our UX is fine with this. Been used for many years and never been a problem or a concern for users afawk :)

**Comment by nicped** [comment]
WCAG support is not only about tags and aria and markup. It is also about usability - like 3 buttons that says "Read more" is not accessible because the limited user cannot navigate using it - technically they might validate.

Either way - you can spend your time getting this to live a little longer, or move along.

**Comment by blackwelllearning** [comment]
Accessibility, Usability and User Experience and SEO are all connected and overlap in so many ways. Oh and keeping to valid coding standards is another big one, I agree.

I would love to keep this going :)

If yourself @nicped or anyone else knows hows to get the repo building as a module I'd be extremely grateful.
