### ISSUE TITLE
Tiny-Slider fails to even start

### ISSUE THREAD

**Issue by ghost** [ganlanyuan/tiny-slider#60]
**Asking a question or submit a bug?**  
- [ ] Question
- [ x] Bug

**How can others reproduce the issue?**  
It can be reproduced by following the "usage" instructions step by step or simply copy pasting them. 

Console error output:

tiny-slider.js:430 Uncaught TypeError: Cannot read property 'appendChild' of null
    at calc (tiny-slider.js:430)
    at tiny-slider.js:748
    at tiny-slider.js:2726
calc @ tiny-slider.js:430
(anonymous) @ tiny-slider.js:748
(anonymous) @ tiny-slider.js:2726
(index):53 Uncaught TypeError: tns is not a function
    at HTMLDocument.<anonymous> ((index):53)

Tiny-slider version:   2.0
Browser version: anything

**Comment by ganlanyuan** [comment]
Will check this on Monday

**Comment by ganlanyuan** [comment]
Hi,
Sorry the document is not clear, actually "tiny-slider.js" need to be put inside the &lt;body&gt; because some functions require `document.body`.   

I just updated "readme":   
https://github.com/ganlanyuan/tiny-slider#1-include-tiny-slider    
https://github.com/ganlanyuan/tiny-slider#3-call-tiny-slider-on-dom-ready   

Could you check it?

**Comment by ganlanyuan** [comment]
Will close it for now.
Feel free to reopen it if the issue still exist.
